require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActionsController do

  # This should return the minimal set of attributes required to create a valid
  # Actions. As you add validations to Actions, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all actions as @actions" do
      actions = Actions.create! valid_attributes
      get :index, {}, valid_session
      assigns(:actions).should eq([actions])
    end
  end

  describe "GET show" do
    it "assigns the requested actions as @actions" do
      actions = Actions.create! valid_attributes
      get :show, {:id => actions.to_param}, valid_session
      assigns(:actions).should eq(actions)
    end
  end

  describe "GET new" do
    it "assigns a new actions as @actions" do
      get :new, {}, valid_session
      assigns(:actions).should be_a_new(Actions)
    end
  end

  describe "GET edit" do
    it "assigns the requested actions as @actions" do
      actions = Actions.create! valid_attributes
      get :edit, {:id => actions.to_param}, valid_session
      assigns(:actions).should eq(actions)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Actions" do
        expect {
          post :create, {:actions => valid_attributes}, valid_session
        }.to change(Actions, :count).by(1)
      end

      it "assigns a newly created actions as @actions" do
        post :create, {:actions => valid_attributes}, valid_session
        assigns(:actions).should be_a(Actions)
        assigns(:actions).should be_persisted
      end

      it "redirects to the created actions" do
        post :create, {:actions => valid_attributes}, valid_session
        response.should redirect_to(Actions.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved actions as @actions" do
        # Trigger the behavior that occurs when invalid params are submitted
        Actions.any_instance.stub(:save).and_return(false)
        post :create, {:actions => {  }}, valid_session
        assigns(:actions).should be_a_new(Actions)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Actions.any_instance.stub(:save).and_return(false)
        post :create, {:actions => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested actions" do
        actions = Actions.create! valid_attributes
        # Assuming there are no other actions in the database, this
        # specifies that the Actions created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Actions.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => actions.to_param, :actions => { "these" => "params" }}, valid_session
      end

      it "assigns the requested actions as @actions" do
        actions = Actions.create! valid_attributes
        put :update, {:id => actions.to_param, :actions => valid_attributes}, valid_session
        assigns(:actions).should eq(actions)
      end

      it "redirects to the actions" do
        actions = Actions.create! valid_attributes
        put :update, {:id => actions.to_param, :actions => valid_attributes}, valid_session
        response.should redirect_to(actions)
      end
    end

    describe "with invalid params" do
      it "assigns the actions as @actions" do
        actions = Actions.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Actions.any_instance.stub(:save).and_return(false)
        put :update, {:id => actions.to_param, :actions => {  }}, valid_session
        assigns(:actions).should eq(actions)
      end

      it "re-renders the 'edit' template" do
        actions = Actions.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Actions.any_instance.stub(:save).and_return(false)
        put :update, {:id => actions.to_param, :actions => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested actions" do
      actions = Actions.create! valid_attributes
      expect {
        delete :destroy, {:id => actions.to_param}, valid_session
      }.to change(Actions, :count).by(-1)
    end

    it "redirects to the actions list" do
      actions = Actions.create! valid_attributes
      delete :destroy, {:id => actions.to_param}, valid_session
      response.should redirect_to(actions_index_url)
    end
  end

end
